# Generated by Django 5.2.17 on 2026-10-03 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(db_index=True, max_length=15)),
                ("code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_used", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="e.g. 0244123456", max_length=15, unique=True
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("bio", models.TextField(blank=True)),
                ("years_of_experience", models.PositiveIntegerField(default=0)),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ashanti", "Ashanti"),
                            ("greater_accra", "Greater Accra"),
                            ("western", "Western"),
                            ("western_north", "Western North"),
                            ("central", "Central"),
                            ("eastern", "Eastern"),
                            ("volta", "Volta"),
                            ("oti", "Oti"),
                            ("northern", "Northern"),
                            ("savannah", "Savannah"),
                            ("north_east", "North East"),
                            ("upper_east", "Upper East"),
                            ("upper_west", "Upper West"),
                            ("bono", "Bono"),
                            ("bono_east", "Bono East"),
                            ("ahafo", "Ahafo"),
                        ],
                        max_length=30,
                    ),
                ),
                ("town", models.CharField(blank=True, max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_photos/"
                    ),
                ),
                (
                    "id_document_front",
                    models.ImageField(blank=True, null=True, upload_to="id_documents/"),
                ),
                (
                    "id_document_back",
                    models.ImageField(blank=True, null=True, upload_to="id_documents/"),
                ),
                ("id_type", models.CharField(blank=True, max_length=30)),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_notes", models.TextField(blank=True)),
                ("is_available", models.BooleanField(default=True)),
                ("rating_avg", models.FloatField(default=0)),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("momo_number", models.CharField(blank=True, max_length=15)),
                (
                    "momo_network",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mtn", "MTN"),
                            ("vodafone", "Telecel/Vodafone"),
                            ("airteltigo", "AirtelTigo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workers",
                        to="services.servicecategory",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
