# Generated by Django 5.2.17 on 2026-10-03 07:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_code",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("client_name", models.CharField(max_length=150)),
                ("client_phone", models.CharField(max_length=15)),
                ("client_location_text", models.CharField(blank=True, max_length=255)),
                ("client_latitude", models.FloatField(blank=True, null=True)),
                ("client_longitude", models.FloatField(blank=True, null=True)),
                ("description", models.TextField()),
                ("preferred_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested — awaiting company review"),
                            (
                                "company_reviewing",
                                "Company confirming worker availability",
                            ),
                            ("worker_confirmed", "Worker confirmed — awaiting payment"),
                            ("in_progress", "Job in progress"),
                            (
                                "completed",
                                "Job marked complete — awaiting client release",
                            ),
                            ("paid_out", "Payment released to worker"),
                            ("declined", "Worker unavailable / declined"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requested",
                        max_length=30,
                    ),
                ),
                (
                    "quoted_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="services.servicecategory",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
